accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path
from .views import ProjectListView, ProjectDetailView, ProjectCreateView


urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from .views import TaskCreateView, TaskListView, TaskUpdateView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

accounts/models.py
# from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return str(self.name)

tasks/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project",
        related_name="tasks",
        on_delete=models.CASCADE,
    )
    assignee = models.ForeignKey(
        USER_MODEL,
        null=True,
        related_name="tasks",
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return str(self.name)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    return render(request, "registration/signup.html", {"form": form})

projects/views.py
# from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Project


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def get_success_url(self):
        return reverse_lazy("show_project", kwargs={"pk": self.object.pk})

tasks/views.py
# from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Task


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self):
        return reverse_lazy(
            "show_project", kwargs={"pk": self.object.project.pk}
        )


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "tasks/update.html"
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="description" content="Django Assessment Project" />
        <meta name="keywords" content="Cool, Django, Project" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Tracker:
            {% block title %}
            {% endblock title %}
        </title>
    </head>
    <body>
        <header>
            {% include 'navbar.html' %}
        </header>
        <main>
            {% block main %}
            {% endblock main %}
        </main>
    </body>
    <!--
  <details>
    <summary>
      Debug Info
    </summary>
    <p>
      <pre>{% debug %}</pre>
    </p>
  </details>
  -->
</html>

projects/templates/navbar.html
<nav>
    <h3>Welcome {{ user.username | default:"Guest" }} !</h3>
    <ul>
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'show_my_tasks' %}">My tasks</a>
            </li>
            <li>
                <a href="{% url 'list_projects' %}">My projects</a>
            </li>
            <li>
                <a href="{% url 'logout' %}">Logout</a>
            </li>
        {% else %}
            <li>
                <a href="{% url 'login' %}">Login</a>
            </li>
            <li>
                <a href="{% url 'signup' %}">Sign Up</a>
            </li>
        {% endif %}
    </ul>
</nav>

projects/templates/projects/create.html
{% extends 'base.html' %}
{% block title %}
    Create a new project
{% endblock title %}
{% block main %}
    <div>
        <h1>Create a new project</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
{% endblock main %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% block title %}
    {{ project.name }}
{% endblock title %}
{% block main %}
    <div>
        <h1>{{ project.name }}</h1>
        {{ project.description|markdownify }}
        <h2>Tasks</h2>
        <p>
            <a href="{% url 'create_task' %}">Create a new task</a>
        </p>
        {% if project.tasks.exists %}
            <table>
                <thead>
                    <th>Name</th>
                    <th>Assignee</th>
                    <th>Start date</th>
                    <th>Due date</th>
                    <th>Is completed</th>
                </thead>
                <tbody>
                    {% for task in project.tasks.all %}
                        <tr>
                            <td>{{ task.name }}</td>
                            <td>{{ task.assignee }}</td>
                            <td>{{ task.start_date|date:"m-d-Y" }}</td>
                            <td>{{ task.due_date|date:"m-d-Y" }}</td>
                            <td>{{ task.is_completed|yesno }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>This project has no tasks</p>
        {% endif %}
    </div>
{% endblock main %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% block title %}
    My Projects
{% endblock title %}
{% block main %}
    <div>
        <h1>My Projects</h1>
        <p>
            <a href="{% url 'create_project' %}">Create a new project</a>
        </p>
        {% if not project_list.exists %}
            <p>You are not assigned to any projects</p>
        {% else %}
            <table>
                <thead>
                    <th>Name</th>
                    <th>Number of tasks</th>
                </thead>
                <tbody>
                    {% for project in project_list %}
                        <tr>
                            <td>
                                <a href="{% url 'show_project' project.id %}">{{ project.name }}</a>
                            </td>
                            <td>{{ project.tasks.all|length }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
{% endblock main %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% block title %}
    Create a new task
{% endblock title %}
{% block main %}
    <div>
        <h1>Create a new task</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
{% endblock main %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% block title %}
    My Tasks
{% endblock title %}
{% block main %}
    <div>
        <h1>My Tasks</h1>
        {% if task_list.exists %}
            <table>
                <thead>
                    <th>Name</th>
                    <th>Start date</th>
                    <th>End date</th>
                    <th>Is completed</th>
                </thead>
                <tbody>
                    {% for task in task_list %}
                        <tr>
                            <td>{{ task.name }}</td>
                            <td>{{ task.start_date|date:"m-d-Y" }}</td>
                            <td>{{ task.due_date|date:"m-d-Y" }}</td>
                            <td>
                                {% if task.is_completed %}
                                    Done
                                {% else %}
                                    <form action="{% url 'complete_task' task.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="is_completed" value="True" />
                                        <button>Complete</button>
                                    </form>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>You have no tasks</p>
        {% endif %}
    </div>
{% endblock main %}